version: "2"
services:
  php:
    image: polux/web-srv:dev
    container_name: web-srv-02
    networks:
        - internal
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/html/php-myged/
      - ../data/app_vault:/var/www/vault/
      - ./logs/apache:/var/log/apache2/
      - ./logs/php:/var/log/php/

  php-ci:
    image: polux/web-ci:dev
    container_name: web-ci-01
    networks:
        - internal
    ports:
      - "8090:8080"
    volumes:
      - ./jenkins-home:/var/jenkins_home

networks:
   internal:
